export const RETURN_HOME = 'RETURN_HOME';
export const RETURN_DISPATCH_SUCCESS = 'RETURN_DISPATCH_SUCCESS';
export const RETURN_DISPATCH_FAIL = 'RETURN_DISPATCH_FAIL';
export const RETURN_DISPATCH_ATTEMPT = 'RETURN_DISPATCH_ATTEMPT';
export const RETURN_SERVICECALLS_ATTEMPT = 'RETURN_SERVICECALLS_ATTEMPT';
export const RETURN_SERVICECALLS_SUCCESS = 'RETURN_SERVICECALLS_SUCCESS';
export const RETURN_SERVICECALLS_FAIL = 'RETURN_SERVICECALLS_FAIL';
