export const RETURN_HOME="RETURN_HOME";

//GET RESPONDERS
export const GET_RESPONDERS_SUCCESS="GET_RESPONDERS_SUCCESS";
export const GET_RESPONDERS_FAIL="GET_RESPONDERS_FAIL";
export const ATTEMPT_GET_RESPONDERS="ATTEMPT_GET_RESPONDERS";